version: "3.8"

services:
  frontend:
    restart: always
    build: .
    volumes:
      - ".:/usr/src/app"
    env_file:
      - .env
    ports:
      - ${REACT_APP_PORT}:3000
    environment:
      - NODE_ENV=development
